trial_name: turnfaucet_spe_phase2_sac_spe7
log_dir: logs
env:
  name: TurnFaucet-v2
  n_env_procs: 32
  obs_mode: state
  act_mode: pd_ee_delta_pose
  seed: 42
  model_ids: 5030,5033,5038,5005,5016
train:
  max_eps_steps: 200
  total_steps: 5000000
  rollout_steps: 5000
  batch_size: 256
  gamma: 0.99
  lr: 0.0003
model_name: SAC
net_arch:
- 256
- 256
model_kwargs:
  verbose: 1
  ent_coef: auto
eval:
  eval_freq: 50
  n_eval_episodes: 10
  n_final_eval_episodes: 100
init_model_path: logs/turnfaucet_gen_phase1_sac/rl_model_12096128_steps.zip
