trial_name: turnfaucet_spe_phase2_sac_spe0_spe1_spe2_spe3_spe4_spe5_spe6_spe7
log_dir: logs
env:
  name: TurnFaucet-v2
  n_env_procs: 32
  obs_mode: state
  act_mode: pd_ee_delta_pose
  seed: 42
  model_ids: 5047,5011,5056,5012,5016
train:
  max_eps_steps: 200
  total_steps: 1500000
  rollout_steps: 5000
  batch_size: 256
  gamma: 0.99
  lr: 0.0003
model_name: SAC
net_arch:
- 256
- 256
model_kwargs:
  verbose: 1
  ent_coef: auto
eval:
  eval_freq: 50
  n_eval_episodes: 10
  n_final_eval_episodes: 100
init_model_path: /kaiming-fast-vol/workspace/CSE291A-ML-for-Robotics-Project2/logs/turnfaucet_gen_phase1_sac/rl_model_11146432_steps.zip
